#自动聊天机器人插件配置
#配置文件的版本，请勿修改！
version: '1.2'
#自动聊天机器人发送消息时显示的名称，如果为空表示不显示
name: '&f[&aAutoChat&f]'
#是否使用字符判断，设置为true后，系统只识别以Char开头的消息
isChar: false
#字符判断的字符
char: '#'
#是否使用权限限制，设置为true后，拥有该权限的人的消息将被机器人忽略
hasPermission: false
#权限限制的权限（建议不要修改！）
permission: 'AutoChat.Ignore'
#是否将机器人的消息发到公屏
isPublic: false
#机器人发送消息的延迟时间，单位：tick
#默认为4tick即200ms
#20tick=1s,1000ms=1s,1tick=50ms
tick: 4
#关键字列表，多个关键字用“,”隔开，关键字和消息之间必须只有“——”，其他地方不允许出现“,”和“——”
#当关键字在列表中的位置越靠前则优先级越高，当出现玩家消息中有多个关键字时，只会识别在列表中最靠前的一个
#可以使用颜色代码
#可以将消息设置成命令，当判断到关键词，自动执行指令（其中@p代指发话的玩家名）
field:
  - '示例关键词1,示例关键词2——示例消息'
  - '示例——/sudo @p spawn'
#命令替换功能
replaceCommand:
#是否启用该功能
  enable: false
#命令替换的列表，采用格式 输入命令:结果命令
#实现的效果，输入/输入命令 <参数>会被替换成/结果命令 <参数>
#参数不会发生任何更改，不能用该方法替换参数
#替换参数的功能将会在未来添加
  list:
    - '回出生点:spawn' #输入 /回出生点 会变成 /spawn
    - '回家:home' #输入 /回家 会变成 /home